# Generated by Django 5.2.1 on 2026-06-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdelegation',
            options={'managed': False, 'verbose_name': 'Delegacao de formulario', 'verbose_name_plural': 'Delegacoes de formularios'},
        ),
    ]
