# Generated by Django 5.2.1 on 2026-06-26 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualificacaoReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('resumo_vagas', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_cursos', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_turmas', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_mulheres', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_homens', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_mercado_fem', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_mercado_masc', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_vagas_ocupadas', models.IntegerField(blank=True, default=0, null=True)),
                ('resumo_taxa_ocupacao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cp_morumbi_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_lagoinha_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_campo_alegre_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_luizote_1_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_luizote_2_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_tocantins_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_planalto_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('onibus_concluintes_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('maravilha_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('uditech_concluintes', models.IntegerField(blank=True, default=0, null=True)),
                ('bairros_visitados', models.IntegerField(blank=True, default=0, null=True)),
                ('concluintes_onibus', models.IntegerField(blank=True, default=0, null=True)),
                ('cursos_onibus', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_morumbi_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_lagoinha_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_campo_alegre_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_luizote_1_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_luizote_2_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_tocantis_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cp_planalto_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('maravilha_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('unitech_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('onibus_atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('cursos_andamento', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio Qualificacao',
                'verbose_name_plural': 'Relatorios Qualificacao',
                'db_table': 'qualificacao_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SineReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('atend_trabalhador', models.IntegerField(blank=True, default=0, null=True)),
                ('atend_online_trabalhador', models.IntegerField(blank=True, default=0, null=True)),
                ('atend_empregador', models.IntegerField(blank=True, default=0, null=True)),
                ('atend_online_empregador', models.IntegerField(blank=True, default=0, null=True)),
                ('seguro_desemprego', models.IntegerField(blank=True, default=0, null=True)),
                ('vagas_captadas', models.IntegerField(blank=True, default=0, null=True)),
                ('ligacoes_recebidas', models.IntegerField(blank=True, default=0, null=True)),
                ('ligacoes_realizadas', models.IntegerField(blank=True, default=0, null=True)),
                ('curriculos', models.IntegerField(blank=True, default=0, null=True)),
                ('entrevistados', models.IntegerField(blank=True, default=0, null=True)),
                ('proc_administrativos', models.IntegerField(blank=True, default=0, null=True)),
                ('processo_seletivo', models.IntegerField(blank=True, default=0, null=True)),
                ('inseridos_mercado', models.IntegerField(blank=True, default=0, null=True)),
                ('carteira_digital', models.IntegerField(blank=True, default=0, null=True)),
                ('orientacao_profissional', models.IntegerField(blank=True, default=0, null=True)),
                ('convocacao_trabalhadores', models.IntegerField(blank=True, default=0, null=True)),
                ('vagas_alto_valor', models.IntegerField(blank=True, default=0, null=True)),
                ('atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio SINE',
                'verbose_name_plural': 'Relatorios SINE',
                'db_table': 'sine_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'managed': False,
            },
        ),
    ]
