# Generated by Django 5.2.1 on 2026-06-26 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaicaReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('finalized', 'Finalizado'), ('submitted', 'Enviado')], default='draft', max_length=20)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('mes_anterior_masc', models.IntegerField(default=0)),
                ('mes_anterior_fem', models.IntegerField(default=0)),
                ('inseridos_masc', models.IntegerField(default=0)),
                ('inseridos_fem', models.IntegerField(default=0)),
                ('desligados_masc', models.IntegerField(default=0)),
                ('desligados_fem', models.IntegerField(default=0)),
                ('total_atendidas', models.IntegerField(default=0)),
                ('atendimentos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Relatorio NAICA',
                'verbose_name_plural': 'Relatorios NAICA',
                'db_table': 'naica_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
